# Cloudflare Pages Configuration for SukiSU-Ultra
name = "sukisu-ultra-docs"
compatibility_date = "2025-08-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "docs/.vitepress/dist"

[env.production]
name = "sukisu-ultra-docs"

[env.preview]
name = "sukisu-ultra-docs-preview"
